name: PR Approvals

on:
  pull_request:

permissions: read-all    

jobs:
  pr-approvals:
    name: PR Approvals
    runs-on: ubuntu-24.04  
    env:
      approvers:
    steps:
      - uses: secureblue/approvals-action@ce28f64903343583dd92c84bffedba124d3a6c95 # v0.1.0
        id: approvers
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          min-required: 1
          approvers: |
            RoyalOughtness
            RKNF404