name: PR Approvals

on:
  pull_request:
    
permissions: {} 

jobs:
  pr-approvals:
    name: PR Approvals
    runs-on: ubuntu-24.04  
    env:
      approvers:
    steps:
      - uses: secureblue/approvals-action@cf33051e1d3a2137da849e42cfd8a7d3609d3b30 # v0.2.5
        id: approvers
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          min-required: 1
          approvers: |
            RoyalOughtness
            RKNF404